openapi: 3.0.3
info:
  title: Office of the Federal Register Agencies Images API
  description: Search, browse and learn about the Federal Register. Federal Register 2.0 is the unofficial daily publication for rules, proposed rules, and notices of Federal agencies and organizations, as well as executive orders and other presidential documents.
  version: v1
  contact:
    name: Office of the Federal Register
    url: https://www.federalregister.gov/developers/documentation/api/v1
servers:
- url: https://www.federalregister.gov/api/v1
  description: Federal Register API
tags:
- name: Images
paths:
  /images/{identifier}:
    get:
      summary: Fetch a Single Image Package
      operationId: getImage
      parameters:
      - name: identifier
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Image package.
      tags:
      - Images
