openapi: 3.0.3
info:
  title: Office of the Federal Register Agencies API
  description: Search, browse and learn about the Federal Register. Federal Register 2.0 is the unofficial daily publication for rules, proposed rules, and notices of Federal agencies and organizations, as well as executive orders and other presidential documents.
  version: v1
  contact:
    name: Office of the Federal Register
    url: https://www.federalregister.gov/developers/documentation/api/v1
servers:
- url: https://www.federalregister.gov/api/v1
  description: Federal Register API
tags:
- name: Agencies
paths:
  /agencies:
    get:
      summary: List Agencies
      description: List all federal agencies represented in the Federal Register.
      operationId: listAgencies
      responses:
        '200':
          description: List of agencies.
      tags:
      - Agencies
  /agencies/{slug}:
    get:
      summary: Fetch a Single Agency
      operationId: getAgency
      parameters:
      - name: slug
        in: path
        required: true
        description: The agency slug.
        schema:
          type: string
      responses:
        '200':
          description: A single agency.
      tags:
      - Agencies
